# Generated by Django 6.1.2 on 2026-10-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('ORDER_PROCESSING', 'Order Processing'), ('ORDER_COMPLETED', 'Order Completed'), ('RFQ_SENT', 'RFQ Sent'), ('RFQ_CANCELLED', 'RFQ Cancelled'), ('QUOTATION_SENT', 'Quotation Sent'), ('QUOTATION_ACCEPTED', 'Quotation Accepted'), ('QUOTATION_REJECTED', 'Quotation Rejected'), ('QUOTATION_CANCELLED', 'Quotation Cancelled'), ('PURCHASE_ORDER_APPROVED', 'Purchase Order Approved'), ('PURCHASE_ORDER_SENT', 'Purchase Order Sent'), ('PURCHASE_ORDER_CANCELLED', 'Purchase Order Cancelled'), ('GOODS_RECEIVED', 'Goods Received')], max_length=50),
        ),
    ]
