# Generated by Django 6.1.1 on 2026-10-01 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_requestforquotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='REQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('ntes', models.TextField(blank=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.requestforquotation')),
            ],
        ),
    ]
