# Generated by Django 6.1.1 on 2026-10-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0003_reqitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='REQItem',
            new_name='RFQItem',
        ),
    ]
