# Generated by Django 6.1.1 on 2026-10-01 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_rename_reqitem_rfqitem'),
    ]

    operations = [
    ]
