# Generated by Django 6.1.2 on 2026-10-08 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_purchaseorder_goodsreceipt_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodReceiptItem',
            new_name='GoodsReceiptItem',
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='suppliers.requestforquotation'),
        ),
    ]
